import React, { useState } from "react";


const cities = [
    {
     name :"Bangalore",
     link:"https://www.swiggy.com/city/bangalore"
    },

    {
     name :"Gurgaon",
     link:"https://www.swiggy.com/city/gurgaon",   
    },

    {
     name :" Hyderabad",
     link:"https://www.swiggy.com/city/hyderabad"   
    },

    {
     name :"Delhi",
     link:"https://www.swiggy.com/city/delhi"  

    },
    {
     name:" Mumbai",
     link:"https://www.swiggy.com/city/mumbai"
    },
    {
     name:"Pune",
     link:"https://www.swiggy.com/city/pune"   
    },
    {
     name:"Kolkata",
     link:"https://www.swiggy.com/city/kolkata"   
    },

    {
     name:"Chennai",
     link:"https://www.swiggy.com/city/chennai"   
    },
    {
     name :"Ahmedabad",
     link:"https://www.swiggy.com/city/ahmedabad" 
    },

    {
     name :"Chandigarh",
     link:"https://www.swiggy.com/city/chandigarh" 
    },

    {
     name :"Jaipur",
     link:"https://www.swiggy.com/city/jaipur" 
    },
    
    {
     name :"Kochi",
     link:"https://www.swiggy.com/city/kochi"
    },
    {
    name :"Coimbatore" ,
    link:"https://www.swiggy.com/city/coimbatore" 
    },
    {
    name :"Lucknow" ,
    link:"https://www.swiggy.com/city/lucknow"   
    },

    {
    name :"Nagpur" ,
    link:"https://www.swiggy.com/city/nagpur"   
    },

    {
    name :"Vadodara" ,
    link:"https://www.swiggy.com/city/vadodara"   
    },

    {
    name :"Indore" ,
    link:"https://www.swiggy.com/city/indore"   
    },
    {
    name :"Guwahati",
    link:"https://www.swiggy.com/city/guwahati"
    },
    {
    name :"Vizag",
    link:"https://www.swiggy.com/city/vizag"
    },
    {
    name :"Surat",
    link:"https://www.swiggy.com/city/surat"
    },
    {
    name :"Dehradun",
    link:"https://www.swiggy.com/city/dehradun"
    },

     {
    name :"Noida",
    link:"https://www.swiggy.com/city/noida"
    },
     {
    name :"Ludhiana",
    link:"https://www.swiggy.com/city/ludhiana"
    },
     {
    name :"Trichy",
    link:"https://www.swiggy.com/city/trichy/order-online"
    },
     {
    name :"Vijayawada",
    link:"https://www.swiggy.com/city/vijayawada"
    },
     {
    name :"Kanpur",
    link:"https://www.swiggy.com/city/kanpur"
    },
     {
    name :"Mysore",
    link:"https://www.swiggy.com/city/mysore"
    },
     {
    name :"Nashik",
    link:"https://www.swiggy.com/city/nashik"
    },
     {
    name :"Udaipur",
    link:"https://www.swiggy.com/city/udaipur"
    },
     {
    name :"Pondicherry",
    link:"https://www.swiggy.com/city/pondicherry"
    },
     {
    name :"Agra",
    link:"https://www.swiggy.com/city/agra"
    },
     {
    name :"Aurangabad",
    link:"https://www.swiggy.com/city/aurangabad"
    },
     {
    name :"Jalandhar",
    link:"https://www.swiggy.com/city/Jalandhar"
    },
     {
    name :"Kota",
    link:"https://www.swiggy.com/city/kota/order-online"
    },
     {
    name :"Madurai",
    link:"https://www.swiggy.com/city/madurai/order-online"
    },
     {
    name :"Allahabad",
    link:"https://www.swiggy.com/city/allahabad/order-online"
    },
     {
    name :" Manipal",
    link:"https://www.swiggy.com/city/manipal/order-online"
    },
     {
    name :"Amritsar",
    link:"https://www.swiggy.com/city/amritsar"
    },
     {
    name :"Bareilly",
    link:"https://www.swiggy.com/city/bareilly/order-online",
    },
     {
    name :"Meerut",
    link:"https://www.swiggy.com/city/meerut/order-online"
    },
     {
    name :"Bhopal",
    link:"https://www.swiggy.com/city/bhopal"
    },
    {
    name :"Ooty",
    link:"https://www.swiggy.com/city/ooty/order-online"
    },
    {
    name :"Bhubaneswar",
    link:"https://www.swiggy.com/city/bhubaneswar"
    },
    {
    name :"Raipur",
    link:"https://www.swiggy.com/city/raipur"
    },
    {
    name:"Bikaner",
    link:"https://www.swiggy.com/city/bikaner/order-online"
    },

    {
    name:"Rajkot",
    link:"https://www.swiggy.com/city/rajkot/order-online"
    },
    {
    name:"Kozhikode",
    link:"https://www.swiggy.com/city/kozhikode/order-online"
    },
    
    {
    name:"Central Goa",
    link:"https://www.swiggy.com/city/central-goa/order-online"
    },
    
    {
    name:"Sirsa",
    link:"https://www.swiggy.com/city/sirsa/order-online"
    },

    {
    name:"Gwalior",
    link:"https://www.swiggy.com/city/gwalior/order-online"
    },


    {
    name:"Thrissur",
    link:"https://www.swiggy.com/city/thrissur/order-online"
    },

    {
    name:"Kharagpur",
    link:"https://www.swiggy.com/city/Kharagpur/order-online"
    },

    {
    name:"Tirupati",
    link:"https://www.swiggy.com/city/Tirupati/order-online"
    },

    {
    name:"Tirupur",
    link:"https://www.swiggy.com/city/Tirupur/order-online"
    },

    {
    name:"Vellore",
    link:"https://www.swiggy.com/city/Vellore/order-online"
    },

    {
    name:"Thiruvananthapuram",
    link:"https://www.swiggy.com/city/Thiruvananthapuram/order-online"
    },

    {
    name:"Warangal",
    link:"https://www.swiggy.com/city/Warangal/order-online"
    },

    {
    name:"Varanasi",
    link:"https://www.swiggy.com/city/Varanasi/order-online"
    },

    {
    name:"Mangaluru",
    link:"https://www.swiggy.com/city/Mangaluru/order-online"
    },

    {
    name:"Patna",
    link:"https://www.swiggy.com/city/Patna/order-online"
    },

    {
    name:"Ranchi",
    link:"https://www.swiggy.com/city/Ranchi/order-online"
    },
    {
    name:"Faridabad",
    link:"https://www.swiggy.com/city/Faridabad/order-online"
    },
    {
    name:"Guntur",
    link:"https://www.swiggy.com/city/Guntur/order-online"
    },
    {
    name:"Ujjain",
    link:"https://www.swiggy.com/city/Ujjain/order-online"
    },
    {
    name:"Patiala",
    link:"https://www.swiggy.com/city/Patiala/order-online"
    },
    {
    name:"Karnal",
    link:"https://www.swiggy.com/city/Karnal/order-online"
    },
    {
    name:"Kakinada",
    link:"https://www.swiggy.com/city/Kakinada/order-online"
    },
    {
    name:"Rajahmundry",
    link:"https://www.swiggy.com/city/Rajahmundry/order-online"
    },
    {
    name:"Bilaspur",
    link:"https://www.swiggy.com/city/Bilaspur/order-online"
    },
    {
    name:"Bhilai",
    link:"https://www.swiggy.com/city/Bhilai/order-online"
    },
    {
    name:"Anand",
    link:"https://www.swiggy.com/city/Anand/order-online"
    },
    {
    name:"Bhavnagar",
    link:"https://www.swiggy.com/city/Bhavnagar/order-online"
    },
    {
    name:"Jammu",
    link:"https://www.swiggy.com/city/Jammu/order-online"
    },
    {
    name:"Muktsar",
    link:"https://www.swiggy.com/city/Muktsar/order-online"
    },

    {
    name:"Panipat",
    link:"https://www.swiggy.com/city/Panipat/order-online"
    },

    {
    name:"Jamshedpur",
    link:"https://www.swiggy.com/city/Jamshedpur/order-online"
    },
    {
    name:"Dhanbad",
    link:"https://www.swiggy.com/city/Dhanbad/order-online"
    },
    {
    name:"Bokaro",
    link:"https://www.swiggy.com/city/Bokaro/order-online"
    },
    {
    name:"Hubli",
    link:"https://www.swiggy.com/city/Hubli/order-online"
    },
    {
    name:"Belgaum",
    link:"https://www.swiggy.com/city/Belgaum/order-online"
    },
    {
    name:"Jabalpur",
    link:"https://www.swiggy.com/city/Jabalpur/order-online"
    },
    {
    name:"Kolhapur",
    link:"https://www.swiggy.com/city/Kolhapur/order-online"
    },
    {
    name:"Solapur",
    link:"https://www.swiggy.com/city/Solapur/order-online"
    },
    {
    name:"Shillong",
    link:"https://www.swiggy.com/city/Shillong/order-online"
    },
    {
    name:"Cuttack",
    link:"https://www.swiggy.com/city/Cuttack/order-online"
    },
    {
    name:"Aligarh",
    link:"https://www.swiggy.com/city/Aligarh/order-online"
    },
    {
    name:"Salem",
    link:"https://www.swiggy.com/city/Salem/order-online"
    },
    {
    name:"Agartala",
    link:"https://www.swiggy.com/city/Agartala/order-online"
    },
    {
    name:"Jodhpur",
    link:"https://www.swiggy.com/city/Jodhpur/order-online"
    },
    {
    name:"Ajmer",
    link:"https://www.swiggy.com/city/Ajmer/order-online"
    },
    {
    name:"Jhansi",
    link:"https://www.swiggy.com/city/Jhansi/order-online"
    },
    {
    name:"Gorakhpur",
    link:"https://www.swiggy.com/city/Gorakhpur/order-online"
    },
    {
    name:"Thanjavur",
    link:"https://www.swiggy.com/city/Thanjavur/order-online"
    },
    {
    name:"Erode",
    link:"https://www.swiggy.com/city/Erode/order-online"
    },
    {
    name:"Nellore",
    link:"https://www.swiggy.com/city/Nellore/order-online"
    },
    {
    name:"Rourkela",
    link:"https://www.swiggy.com/city/Rourkela/order-online"
    },
    {
    name:"Anantapur",
    link:"https://www.swiggy.com/city/Anantapur/order-online"
    },
    {
    name:"Kurnool",
    link:"https://www.swiggy.com/city/Kurnool/order-online"
    },
    {
    name:"Ahmednagar",
    link:"https://www.swiggy.com/city/Ahmednagar/order-online"
    },
    {
    name:"Phagwara",
    link:"https://www.swiggy.com/city/Phagwara/order-online"
    },
    {
    name:"Ambala",
    link:"https://www.swiggy.com/city/Ambala/order-online"
    },
    {
    name:"Ballari",
    link:"https://www.swiggy.com/city/Ballari/order-online"
    },
    {
    name:"Saharanpur",
    link:"https://www.swiggy.com/city/Saharanpur/order-online"
    },
    {
    name:"Tirunelveli",
    link:"https://www.swiggy.com/city/Tirunelveli/order-online"
    },
    {
    name:"Bathinda",
    link:"https://www.swiggy.com/city/Bathinda/order-online"
    },
    {
    name:"Mathura",
    link:"https://www.swiggy.com/city/Mathura/order-online"
    },
    {
    name:"Haridwar",
    link:"https://www.swiggy.com/city/Haridwar/order-online"
    },
    {
    name:"Ratnagiri",
    link:"https://www.swiggy.com/city/Ratnagiri/order-online"
    },
    {
    name:"Sangli",
    link:"https://www.swiggy.com/city/Sangli/order-online"
    },
    {
    name:"Amravati",
    link:"https://www.swiggy.com/city/Amravati/order-online"
    },
    {
    name:"Rishikesh",
    link:"https://www.swiggy.com/city/Rishikesh/order-online"
    },
    {
    name:"Nagercoil",
    link:"https://www.swiggy.com/city/Nagercoil/order-online"
    },
    {
    name:"KanyaKumari",
    link:"https://www.swiggy.com/city/KanyaKumari/order-online"
    },
    {
    name:"Kadapa",
    link:"https://www.swiggy.com/city/Kadapa/order-online"
    },
    {
    name:"Nizamabad",
    link:"https://www.swiggy.com/city/Nizamabad/order-online"
    },
    {
    name:"Shivamogga",
    link:"https://www.swiggy.com/city/Shivamogga/order-online"
    },
    {
    name:"Davanagere",
    link:"https://www.swiggy.com/city/Davanagere/order-online"
    },
    {
    name:"Roorkee",
    link:"https://www.swiggy.com/city/Roorkee/order-online"
    },
    {
    name:"Nanded",
    link:"https://www.swiggy.com/city/Nanded/order-online"
    },
    {
    name:"Rewa",
    link:"https://www.swiggy.com/city/Rewa/order-online"
    },
    {
    name:"Satna",
    link:"https://www.swiggy.com/city/Satna/order-online"
    },
    {
    name:"Shimla",
    link:"https://www.swiggy.com/city/Shimla/order-online"
    },
    {
    name:"Muzaffarpur",
    link:"https://www.swiggy.com/city/Muzaffarpur/order-online"
    },
    {
    name:"Valsad",
    link:"https://www.swiggy.com/city/Valsad/order-online"
    },
    {
    name:"Vapi",
    link:"https://www.swiggy.com/city/Vapi/order-online"
    },
    {
    name:"Chhapra",
    link:"https://www.swiggy.com/city/Chhapra/order-online"
    },
    {
    name:"Dharamshala",
    link:"https://www.swiggy.com/city/Dharamshala/order-online"
    },
    {
    name:"Kollam",
    link:"https://www.swiggy.com/city/Kollam/order-online"
    },
    {
    name:"Silchar",
    link:"https://www.swiggy.com/city/Silchar/order-online"
    },
    {
    name:"Alappuzha",
    link:"https://www.swiggy.com/city/Alappuzha/order-online"
    },
    {
    name:"Sonipat",
    link:"https://www.swiggy.com/city/Sonipat/order-online"
    },
    {
    name:"Rohtak",
    link:"https://www.swiggy.com/city/Rohtak/order-online"
    },
    {
    name:"Mehsana",
    link:"https://www.swiggy.com/city/Mehsana/order-online"
    },
    {
    name:"Kullu",
    link:"https://www.swiggy.com/city/Kullu/order-online"
    },
    {
    name:"Dhule",
    link:"https://www.swiggy.com/city/Dhule/order-online"
    },
    {
    name:"Dharwad",
    link:"https://www.swiggy.com/city/Dharwad/order-online"
    },
    {
    name:"Latur",
    link:"https://www.swiggy.com/city/Latur/order-online"
    },
    {
    name:"Vizianagaram",
    link:"https://www.swiggy.com/city/Vizianagaram/order-online"
    },
    {
    name:"Khammam",
    link:"https://www.swiggy.com/city/Khammam/order-online"
    },
    {
    name:"Hampi",
    link:"https://www.swiggy.com/city/Hampi/order-online"
    },
    {
    name:"Nainital",
    link:"https://www.swiggy.com/city/Nainital/order-online"
    },
    {
    name:"Akola",
    link:"https://www.swiggy.com/city/Akola/order-online"
    },
    {
    name:"Kalaburagi",
    link:"https://www.swiggy.com/city/Kalaburagi/order-online"
    },
    {
    name:"Gaya",
    link:"https://www.swiggy.com/city/Gaya/order-online"
    },
    {
    name:"Muzaffarnagar",
    link:"https://www.swiggy.com/city/Muzaffarnagar/order-online"
    },
    {
    name:"Dewas",
    link:"https://www.swiggy.com/city/Dewas/order-online"
    },
    {
    name:"Korba",
    link:"https://www.swiggy.com/city/Korba/order-online"
    },
    {
    name:"Mussoorie",
    link:"https://www.swiggy.com/city/Mussoorie/order-online"
    },
    {
    name:"Jalgaon",
    link:"https://www.swiggy.com/city/Jalgaon/order-online"
    },
    {
    name:"Yamuna Nagar",
    link:"https://www.swiggy.com/city/Yamuna Nagar/order-online"
    },
    {
    name:"Bhagalpur",
    link:"https://www.swiggy.com/city/Bhagalpur/order-online"
    },
    {
    name:"Hapur",
    link:"https://www.swiggy.com/city/Hapur/order-online"
    },
    {
    name:"Morena",
    link:"https://www.swiggy.com/city/Morena/order-online"
    },
    {
    name:"Hassan",
    link:"https://www.swiggy.com/city/Hassan/order-online"
    },
    {
    name:"Hisar",
    link:"https://www.swiggy.com/city/Hisar/order-online"
    },
    {
    name:"Godhra",
    link:"https://www.swiggy.com/city/Godhra/order-online"
    },
    {
    name:"Kolar",
    link:"https://www.swiggy.com/city/Kolar/order-online"
    },
    {
    name:"Rampur",
    link:"https://www.swiggy.com/city/Rampur/order-online"
    },
    {
    name:"Sitapur",
    link:"https://www.swiggy.com/city/Sitapur/order-online"
    },
    {
    name:"Etawah",
    link:"https://www.swiggy.com/city/Etawah/order-online"
    },
    {
    name:"Porbandar",
    link:"https://www.swiggy.com/city/Porbandar/order-online"
    },
    {
    name:"Nadiad",
    link:"https://www.swiggy.com/city/Nadiad/order-online"
    },
    {
    name:"Sagar",
    link:"https://www.swiggy.com/city/Sagar/order-online"
    },
    {
    name:"Morbi",
    link:"https://www.swiggy.com/city/Morbi/order-online"
    },
    {
    name:"Chhindwara",
    link:"https://www.swiggy.com/city/Chhindwara/order-online"
    },
    {
    name:"Tumakuru",
    link:"https://www.swiggy.com/city/Tumakuru/order-online"
    },
    {
    name:"Singrauli",
    link:"https://www.swiggy.com/city/Singrauli/order-online"
    },
    {
    name:"Thoothukudi",
    link:"https://www.swiggy.com/city/Thoothukudi/order-online"
    },
    {
    name:"Katni",
    link:"https://www.swiggy.com/city/Katni/order-online"
    },
    {
    name:"Khandwa",
    link:"https://www.swiggy.com/city/Khandwa/order-online"
    },
    {
    name:"Eluru",
    link:"https://www.swiggy.com/city/Eluru/order-online"
    },
    {
    name:"Malappuram",
    link:"https://www.swiggy.com/city/Malappuram/order-online"
    },
    {
    name:"Dibrugarh",
    link:"https://www.swiggy.com/city/Dibrugarh/order-online"
    },
    {
    name:"Deoghar",
    link:"https://www.swiggy.com/city/Deoghar/order-online"
    },
    {
    name:"Khanna",
    link:"https://www.swiggy.com/city/Khanna/order-online"
    },
    {
    name:"Bidar",
    link:"https://www.swiggy.com/city/Bidar/order-online"
    },
    {
    name:"Anantnag",
    link:"https://www.swiggy.com/city/Anantnag/order-online"
    },
    {
    name:"Madikeri",
    link:"https://www.swiggy.com/city/Madikeri/order-online"
    },
    {
    name:"Haldwani",
    link:"https://www.swiggy.com/city/Haldwani/order-online"
    },
    {
    name:"Panchkula",
    link:"https://www.swiggy.com/city/Panchkula/order-online"
    },
    {
    name:"Farrukhabad",
    link:"https://www.swiggy.com/city/Farrukhabad/order-online"
    },
    {
    name:"Malegaon",
    link:"https://www.swiggy.com/city/Malegaon/order-online"
    },
    {
    name:"Dindigul",
    link:"https://www.swiggy.com/city/Dindigul/order-online"
    },
    {
    name:"Shahjahanpur",
    link:"https://www.swiggy.com/city/Shahjahanpur/order-online"
    },
    {
    name:"Beed",
    link:"https://www.swiggy.com/city/Beed/order-online"
    },
    {
    name:"Junagadh",
    link:"https://www.swiggy.com/city/Junagadh/order-online"
    },
    {
    name:"Asansol",
    link:"https://www.swiggy.com/city/Asansol/order-online"
    },
    {
    name:"Beawar",
    link:"https://www.swiggy.com/city/Beawar/order-online"
    },
    {
    name:"Kishangarh",
    link:"https://www.swiggy.com/city/Kishangarh/order-online"
    },
    {
    name:"Budhwal",
    link:"https://www.swiggy.com/city/Budhwal/order-online"
    },
    {
    name:"Parbhani",
    link:"https://www.swiggy.com/city/Parbhani/order-online"
    },
    {
    name:"Gondia",
    link:"https://www.swiggy.com/city/Gondia/order-online"
    },
    {
    name:"Ichalkaranji",
    link:"https://www.swiggy.com/city/Ichalkaranji/order-online"
    },
    {
    name:"Jalna",
    link:"https://www.swiggy.com/city/Jalna/order-online"
    },
    {
    name:"Yavatmal",
    link:"https://www.swiggy.com/city/Yavatmal/order-online"
    },
    {
    name:"Shivpuri",
    link:"https://www.swiggy.com/city/Shivpuri/order-online"
    },
    {
    name:"Moga",
    link:"https://www.swiggy.com/city/Moga/order-online"
    },
    {
    name:"Abohar",
    link:"https://www.swiggy.com/city/Abohar/order-online"
    },
    {
    name:"Adoni",
    link:"https://www.swiggy.com/city/Adoni/order-online"
    },
    {
    name:"Madanapalle",
    link:"https://www.swiggy.com/city/Madanapalle/order-online"
    },
    {
    name:"Tiruvannamalai",
    link:"https://www.swiggy.com/city/Tiruvannamalai/order-online"
    },
    {
    name:"Satara",
    link:"https://www.swiggy.com/city/Satara/order-online"
    },
    {
    name:"Ambur",
    link:"https://www.swiggy.com/city/Ambur/order-online"
    },
    {
    name:"Karimnagar",
    link:"https://www.swiggy.com/city/Karimnagar/order-online"
    },
    {
    name:"Ratlam",
    link:"https://www.swiggy.com/city/Ratlam/order-online"
    },
    {
    name:"Moradabad",
    link:"https://www.swiggy.com/city/Moradabad/order-online"
    },
    {
    name:"Machilipatnam",
    link:"https://www.swiggy.com/city/Machilipatnam/order-online"
    },
    {
    name:"Ongole",
    link:"https://www.swiggy.com/city/Ongole/order-online"
    },
    {
    name:"Kottayam",
    link:"https://www.swiggy.com/city/Kottayam/order-online"
    },
    {
    name:"Darbhanga",
    link:"https://www.swiggy.com/city/Darbhanga/order-online"
    },
    {
    name:"Kurukshetra",
    link:"https://www.swiggy.com/city/Kurukshetra/order-online"
    },
    {
    name:"Unnao",
    link:"https://www.swiggy.com/city/Unnao/order-online"
    },
    {
    name:"Bulandshahr",
    link:"https://www.swiggy.com/city/Bulandshahr/order-online"
    },
    {
    name:"Durgapur",
    link:"https://www.swiggy.com/city/Durgapur/order-online"
    },
    {
    name:"Pali",
    link:"https://www.swiggy.com/city/Pali/order-online"
    },
    {
    name:"Tadepalligudem",
    link:"https://www.swiggy.com/city/Tadepalligudem/order-online"
    },
    {
    name:"Ramagundam",
    link:"https://www.swiggy.com/city/Ramagundam/order-online"
    },
    {
    name:"Mahbubnagar",
    link:"https://www.swiggy.com/city/Mahbubnagar/order-online"
    },
    {
    name:"Bhiwani",
    link:"https://www.swiggy.com/city/Bhiwani/order-online"
    },
    {
    name:"Cuddalore",
    link:"https://www.swiggy.com/city/Cuddalore/order-online"
    },
    {
    name:"Kaithal",
    link:"https://www.swiggy.com/city/Kaithal/order-online"
    },
    {
    name:"Jagtial",
    link:"https://www.swiggy.com/city/Jagtial/order-online"
    },
    {
    name:"Palakkad",
    link:"https://www.swiggy.com/city/Palakkad/order-online"
    },
    {
    name:"Guna",
    link:"https://www.swiggy.com/city/Guna/order-online"
    },
    {
    name:"Kumbakonam",
    link:"https://www.swiggy.com/city/Kumbakonam/order-online"
    },
    {
    name:"Maunath Bhanjan",
    link:"https://www.swiggy.com/city/Maunath Bhanjan/order-online"
    },
    {
    name:"Baripada",
    link:"https://www.swiggy.com/city/Baripada/order-online"
    },
    {
    name:"Orai",
    link:"https://www.swiggy.com/city/Orai/order-online"
    },
    {
    name:"Bhadrak",
    link:"https://www.swiggy.com/city/Bhadrak/order-online"
    },
    {
    name:"Batala",
    link:"https://www.swiggy.com/city/Batala/order-online"
    },
    {
    name:"Firozpur",
    link:"https://www.swiggy.com/city/Firozpur/order-online"
    },
    {
    name:"Barnala",
    link:"https://www.swiggy.com/city/Barnala/order-online"
    },
    {
    name:"Raigarh",
    link:"https://www.swiggy.com/city/Raigarh/order-online"
    },
    {
    name:"Nagaon",
    link:"https://www.swiggy.com/city/Nagaon/order-online"
    },
    {
    name:"Mainpuri",
    link:"https://www.swiggy.com/city/Mainpuri/order-online"
    },
    {
    name:"Balurghat",
    link:"https://www.swiggy.com/city/Balurghat/order-online"
    },
    {
    name:"Giridih",
    link:"https://www.swiggy.com/city/Giridih/order-online"
    },
    {
    name:"Ghazipur",
    link:"https://www.swiggy.com/city/Ghazipur/order-online"
    },
    {
    name:"Jagdalpur",
    link:"https://www.swiggy.com/city/Jagdalpur/order-online"
    },
    {
    name:"Vidisha",
    link:"https://www.swiggy.com/city/Vidisha/order-online"
    },
    {
    name:"Dimapur",
    link:"https://www.swiggy.com/city/Dimapur/order-online"
    },
    {
    name:"Shikohabad",
    link:"https://www.swiggy.com/city/Shikohabad/order-online"
    },
    {
    name:"Imphal",
    link:"https://www.swiggy.com/city/sirsa/order-online"
    },
    {
    name:"Lakhimpur",
    link:"https://www.swiggy.com/city/sirsa/order-online"
    },
    {
    name:"Rudrapur",
    link:"https://www.swiggy.com/city/Rudrapur/order-online"
    },
    {
    name:"Ambikapur",
    link:"https://www.swiggy.com/city/Ambikapur/order-online"
    },
    {
    name:"Damoh",
    link:"https://www.swiggy.com/city/Damoh/order-online"
    },
    {
    name:"Rae Bareli",
    link:"https://www.swiggy.com/city/Rae Bareli/order-online"
    },
    {
    name:"Tinsukia",
    link:"https://www.swiggy.com/city/Tinsukia/order-online"
    },
    {
    name:"Rajapalayam",
    link:"https://www.swiggy.com/city/Rajapalayam/order-online"
    },
    {
    name:"Rajnandgaon",
    link:"https://www.swiggy.com/city/Rajnandgaon/order-online"
    },
    {
    name:"Kashipur",
    link:"https://www.swiggy.com/city/Kashipur/order-online"
    },
    {
    name:"Ranibennur",
    link:"https://www.swiggy.com/city/Ranibennur/order-online"
    },
    {
    name:"Burhanpur",
    link:"https://www.swiggy.com/city/Burhanpur/order-online"
    },
    {
    name:"Bhadravati",
    link:"https://www.swiggy.com/city/Bhadravati/order-online"
    },
    {
    name:"Chittoor",
    link:"https://www.swiggy.com/city/Chittoor/order-online"
    },
    {
    name:"Pudukkottai",
    link:"https://www.swiggy.com/city/Pudukkottai/order-online"
    },
    {
    name:"Hardoi",
    link:"https://www.swiggy.com/city/Hardoi/order-online"
    },
    {
    name:"Basti",
    link:"https://www.swiggy.com/city/Basti/order-online"
    },
    {
    name:"Karaikkudi",
    link:"https://www.swiggy.com/city/Karaikkudi/order-online"
    },
    {
    name:"Lalitpur",
    link:"https://www.swiggy.com/city/Lalitpur/order-online"
    },
    {
    name:"Hospet",
    link:"https://www.swiggy.com/city/Hospet/order-online"
    },
    {
    name:"Budaun",
    link:"https://www.swiggy.com/city/Budaun/order-online"
    },
    {
    name:"Neemuch",
    link:"https://www.swiggy.com/city/Neemuch/order-online"
    },
    {
    name:"Pilibhit",
    link:"https://www.swiggy.com/city/Pilibhit/order-online"
    },
    {
    name:"Amroha",
    link:"https://www.swiggy.com/city/Amroha/order-online"
    },
    {
    name:"Barshi",
    link:"https://www.swiggy.com/city/Barshi/order-online"
    },
    {
    name:"Sri Ganganagar",
    link:"https://www.swiggy.com/city/Sri Ganganagar/order-online"
    },
    {
    name:"Wardha",
    link:"https://www.swiggy.com/city/Wardha/order-online"
    },
    {
    name:"Sehore",
    link:"https://www.swiggy.com/city/Sehore/order-online"
    },
    {
    name:"Bhimavaram",
    link:"https://www.swiggy.com/city/Bhimavaram/order-online"
    },
    {
    name:"Hanumangarh",
    link:"https://www.swiggy.com/city/Hanumangarh/order-online"
    },
    {
    name:"Pathankot",
    link:"https://www.swiggy.com/city/Pathankot/order-online"
    },
    {
    name:"Puri",
    link:"https://www.swiggy.com/city/Puri/order-online"
    },
    {
    name:"Fatehpur",
    link:"https://www.swiggy.com/city/Fatehpur/order-online"
    },
    {
    name:"Dudhrej",
    link:"https://www.swiggy.com/city/Dudhrej/order-online"
    },
    {
    name:"Jamnagar",
    link:"https://www.swiggy.com/city/Jamnagar/order-online"
    },
    {
    name:"Bhuj",
    link:"https://www.swiggy.com/city/Bhuj/order-online"
    },
    {
    name:"Gandhidham",
    link:"https://www.swiggy.com/city/Gandhidham/order-online"
    },
    {
    name:"Bharuch",
    link:"https://www.swiggy.com/city/Bharuch/order-online"
    },
    {
    name:"Navsari",
    link:"https://www.swiggy.com/city/Navsari/order-online"
    },
    {
    name:"Amreli",
    link:"https://www.swiggy.com/city/Amreli/order-online"
    },
    {
    name:"Palanpur",
    link:"https://www.swiggy.com/city/Palanpur/order-online"
    },
    {
    name:"Bhilwara",
    link:"https://www.swiggy.com/city/Bhilwara/order-online"
    },
    {
    name:"Suratgarh",
    link:"https://www.swiggy.com/city/Suratgarh/order-online"
    },
    {
    name:"Sikar",
    link:"https://www.swiggy.com/city/Sikar/order-online"
    },
    {
    name:"Churu",
    link:"https://www.swiggy.com/city/Churu/order-online"
    },
    {
    name:"Alwar",
    link:"https://www.swiggy.com/city/Alwar/order-online"
    },
    {
    name:"Bhiwadi",
    link:"https://www.swiggy.com/city/Bhiwadi/order-online"
    },
    {
    name:"Bharatpur",
    link:"https://www.swiggy.com/city/Bharatpur/order-online"
    },
    {
    name:"Mount Abu",
    link:"https://www.swiggy.com/city/Mount Abu/order-online"
    },
    {
    name:"Bundi",
    link:"https://www.swiggy.com/city/Bundi/order-online"
    },
    {
    name:"Sawai Madhopur",
    link:"https://www.swiggy.com/city/Sawai Madhopur/order-online"
    },
    {
    name:"Purulia",
    link:"https://www.swiggy.com/city/Purulia/order-online"
    },
    {
    name:"Bardhaman",
    link:"https://www.swiggy.com/city/Bardhaman/order-online"
    },
    {
    name:"Raniganj",
    link:"https://www.swiggy.com/city/Raniganj/order-online"
    },
    {
    name:"Darjeeling",
    link:"https://www.swiggy.com/city/Darjeeling/order-online"
    },
    {
    name:"Jalpaiguri",
    link:"https://www.swiggy.com/city/Jalpaiguri/order-online"
    },
    {
    name:"Chittorgarh",
    link:"https://www.swiggy.com/city/Chittorgarh/order-online"
    },
    {
    name:"Dholpur",
    link:"https://www.swiggy.com/city/Dholpur/order-online"
    },
    {
    name:"Uluberia",
    link:"https://www.swiggy.com/city/Uluberia/order-online"
    },
    {
    name:"Nabadwip",
    link:"https://www.swiggy.com/city/Nabadwip/order-online"
    },
    {
    name:"Bongaon",
    link:"https://www.swiggy.com/city/Bongaon/order-online"
    },
    {
    name:"Kanchrapara",
    link:"https://www.swiggy.com/city/Kanchrapara/order-online"
    },
    {
    name:"Bankura",
    link:"https://www.swiggy.com/city/Bankura/order-online"
    },
    {
    name:"Habra",
    link:"https://www.swiggy.com/city/Habra/order-online"
    },
    {
    name:"Firozabad",
    link:"https://www.swiggy.com/city/Firozabad/order-online"
    },
    {
    name:"Tadpatri",
    link:"https://www.swiggy.com/city/Tadpatri/order-online"
    },
    {
    name:"Gonda",
    link:"https://www.swiggy.com/city/Gonda/order-online"
    },
    {
    name:"Mughalsarai",
    link:"https://www.swiggy.com/city/Mughalsarai/order-online"
    },
    {
    name:"Medinipur",
    link:"https://www.swiggy.com/city/Medinipur/order-online"
    },
    {
    name:"Nagda",
    link:"https://www.swiggy.com/city/Nagda/order-online"
    },
    {
    name:"Chilakaluripet",
    link:"https://www.swiggy.com/city/Chilakaluripet/order-online"
    },
    {
    name:"Hindupur",
    link:"https://www.swiggy.com/city/Hindupur/order-online"
    },
    {
    name:"Kasganj",
    link:"https://www.swiggy.com/city/Kasganj/order-online"
    },
    {
    name:"Raiganj",
    link:"https://www.swiggy.com/city/Raiganj/order-online"
    },
    {
    name:"Deoria City",
    link:"https://www.swiggy.com/city/Deoria City/order-online"
    },
    {
    name:"Sultanpur",
    link:"https://www.swiggy.com/city/Sultanpur/order-online"
    },
    {
    name:"Shamli",
    link:"https://www.swiggy.com/city/Shamli/order-online"
    },
    {
    name:"Krishnanagar",
    link:"https://www.swiggy.com/city/Krishnanagar/order-online"
    },
    {
    name:"Ballia",
    link:"https://www.swiggy.com/city/Ballia/order-online"
    },
    {
    name:"Guntakal",
    link:"https://www.swiggy.com/city/Guntakal/order-online"
    },
    {
    name:"Miryalaguda",
    link:"https://www.swiggy.com/city/Miryalaguda/order-online"
    },
    {
    name:"Etah",
    link:"https://www.swiggy.com/city/Etah/order-online"
    },
    {
    name:"Berhampore",
    link:"https://www.swiggy.com/city/Berhampore/order-online"
    },
    {
    name:"Gudivada",
    link:"https://www.swiggy.com/city/Gudivada/order-online"
    },
    {
    name:"Haldia",
    link:"https://www.swiggy.com/city/Haldia/order-online"
    },
    {
    name:"Santipur",
    link:"https://www.swiggy.com/city/Santipur/order-online"
    },
    {
    name:"Basirhat",
    link:"https://www.swiggy.com/city/Basirhat/order-online"
    },
    {
    name:"Seoni",
    link:"https://www.swiggy.com/city/Seoni/order-online"
    },
    {
    name:"Udgir",
    link:"https://www.swiggy.com/city/Udgir/order-online"
    },
    {
    name:"Proddatur",
    link:"https://www.swiggy.com/city/Proddatur/order-online"
    },
    {
    name:"Nagapattinam",
    link:"https://www.swiggy.com/city/Nagapattinam/order-online"
    },
    {
    name:"Chikmagalur",
    link:"https://www.swiggy.com/city/Chikmagalur/order-online"
    },
    {
    name:"Chandausi",
    link:"https://www.swiggy.com/city/Chandausi/order-online"
    },
    {
    name:"Bhind",
    link:"https://www.swiggy.com/city/Bhind/order-online"
    },
    {
    name:"Mandya",
    link:"https://www.swiggy.com/city/Mandya/order-online"
    },
    {
    name:"Bagalkot",
    link:"https://www.swiggy.com/city/Bagalkot/order-online"
    },
    {
    name:"Nandurbar",
    link:"https://www.swiggy.com/city/Nandurbar/order-online"
    },
    {
    name:"Chitradurga",
    link:"https://www.swiggy.com/city/Chitradurga/order-online"
    },
    {
    name:"Osmanabad",
    link:"https://www.swiggy.com/city/Osmanabad/order-online"
    },
    {
    name:"Modinagar",
    link:"https://www.swiggy.com/city/Modinagar/order-online"
    },
    {
    name:"Gadag-Betigeri",
    link:"https://www.swiggy.com/city/Gadag-Betigeri/order-online"
    },
    {
    name:"Hoshangabad",
    link:"https://www.swiggy.com/city/Hoshangabad/order-online"
    },
    {
    name:"Jaunpur",
    link:"https://www.swiggy.com/city/Jaunpur/order-online"
    },
    {
    name:"Khurja",
    link:"https://www.swiggy.com/city/Khurja/order-online"
    },
    {
    name:"Port Blair",
    link:"https://www.swiggy.com/city/Port Blair/order-online"
    },
    {
    name:"Jorhat",
    link:"https://www.swiggy.com/city/Jorhat/order-online"
    },
    {
    name:"Nandyal",
    link:"https://www.swiggy.com/city/Nandyal/order-online"
    },
    {
    name:"Biharsharif",
    link:"https://www.swiggy.com/city/Biharsharif/order-online"
    },
    {
    name:"Buxar",
    link:"https://www.swiggy.com/city/Buxar/order-online"
    },
    {
    name:"Siwan",
    link:"https://www.swiggy.com/city/Siwan/order-online"
    },
    {
    name:"Dehri",
    link:"https://www.swiggy.com/city/Dehri/order-online"
    },
    {
    name:"Bettiah",
    link:"https://www.swiggy.com/city/Bettiah/order-online"
    },
    {
    name:"Kishanganj",
    link:"https://www.swiggy.com/city/Kishanganj/order-online"
    },
    {
    name:"Saharsa",
    link:"https://www.swiggy.com/city/Saharsa/order-online"
    },
    {
    name:"Hajipur",
    link:"https://www.swiggy.com/city/Hajipur/order-online"
    },
    {
    name:"Motihari",
    link:"https://www.swiggy.com/city/Motihari/order-online"
    },
    {
    name:"Sasaram",
    link:"https://www.swiggy.com/city/Sasaram/order-online"
    },
    {
    name:"Munger",
    link:"https://www.swiggy.com/city/Munger/order-online"
    },
    {
    name:"Katihar",
    link:"https://www.swiggy.com/city/Katihar/order-online"
    },
    {
    name:"Arrah",
    link:"https://www.swiggy.com/city/Arrah/order-online"
    },
    {
    name:"Srikakulam",
    link:"https://www.swiggy.com/city/Srikakulam/order-online"
    },
    {
    name:"Begusarai",
    link:"https://www.swiggy.com/city/Begusarai/order-online"
    },
    {
    name:"Neyveli",
    link:"https://www.swiggy.com/city/Neyveli/order-online"
    },
    {
    name:"Waidhan",
    link:"https://www.swiggy.com/city/Waidhan/order-online"
    },
    {
    name:"Markapur",
    link:"https://www.swiggy.com/city/Markapur/order-online"
    },
    {
    name:"Chikkaballapur",
    link:"https://www.swiggy.com/city/Chikkaballapur/order-online"
    },
    {
    name:"Bhatkal",
    link:"https://www.swiggy.com/city/Bhatkal/order-online"
    },
    {
    name:"Gokak",
    link:"https://www.swiggy.com/city/Gokak/order-online"
    },
    {
    name:"Itarsi",
    link:"https://www.swiggy.com/city/Itarsi/order-online"
    },
    {
    name:"Dabra",
    link:"https://www.swiggy.com/city/Dabra/order-online"
    },
    {
    name:"Dhar",
    link:"https://www.swiggy.com/city/Dhar/order-online"
    },
    {
    name:"Chalisgaon",
    link:"https://www.swiggy.com/city/Chalisgaon/order-online"
    },
    {
    name:"Thiruvallur",
    link:"https://www.swiggy.com/city/Thiruvallur/order-online"
    },
    {
    name:"Namakkal",
    link:"https://www.swiggy.com/city/Namakkal/order-online"
    },
    {
    name:"Dharmapuri",
    link:"https://www.swiggy.com/city/Dharmapuri/order-online"
    },
    {
    name:"Bhandara",
    link:"https://www.swiggy.com/city/Bhandara/order-online"
    },
    {
    name:"Virudhunagar",
    link:"https://www.swiggy.com/city/Virudhunagar/order-online"
    },
    {
    name:"Siddipet",
    link:"https://www.swiggy.com/city/Siddipet/order-online"
    },
    {
    name:"Gadwal",
    link:"https://www.swiggy.com/city/Gadwal/order-online"
    },
    {
    name:"Bodhan-Rural",
    link:"https://www.swiggy.com/city/Bodhan-Rural/order-online"
    },
    {
    name:"Kamareddy",
    link:"https://www.swiggy.com/city/Kamareddy/order-online"
    },
    {
    name:"Jhunjhunu",
    link:"https://www.swiggy.com/city/Jhunjhunu/order-online"
    },
    {
    name:"Kapurthala",
    link:"https://www.swiggy.com/city/Kapurthala/order-online"
    },
    {
    name:"Sangrur",
    link:"https://www.swiggy.com/city/Sangrur/order-online"
    },
    {
    name:"Gurdaspur",
    link:"https://www.swiggy.com/city/Gurdaspur/order-online"
    },
    {
    name:"Ramgarh",
    link:"https://www.swiggy.com/city/Ramgarh/order-online"
    },
    {
    name:"Bantwal",
    link:"https://www.swiggy.com/city/Bantwal/order-online"
    },
    {
    name:"Doddaballapura",
    link:"https://www.swiggy.com/city/Doddaballapura/order-online"
    },
    {
    name:"Buldana",
    link:"https://www.swiggy.com/city/Buldana/order-online"
    },
    {
    name:"Karad",
    link:"https://www.swiggy.com/city/Karad/order-online"
    },
    {
    name:"Krishnagiri",
    link:"https://www.swiggy.com/city/Krishnagiri/order-online"
    },
    {
    name:"Tiptur",
    link:"https://www.swiggy.com/city/Tiptur/order-online"
    },
    {
    name:"Bhadrachalam",
    link:"https://www.swiggy.com/city/Bhadrachalam/order-online"
    },
    {
    name:"Mancherial",
    link:"https://www.swiggy.com/city/Mancherial/order-online"
    },
    {
    name:"Balrampur",
    link:"https://www.swiggy.com/city/Balrampur/order-online"
    },
    {
    name:"Bharabanki",
    link:"https://www.swiggy.com/city/Bharabanki/order-online"
    },
    {
    name:"Malout",
    link:"https://www.swiggy.com/city/Malout/order-online"
    },
    {
    name:"Fatehgarh Sahib",
    link:"https://www.swiggy.com/city/Fatehgarh Sahib/order-online"
    },
    {
    name:"Ropar",
    link:"https://www.swiggy.com/city/Ropar/order-online"
    },
    {
    name:"Nangal",
    link:"https://www.swiggy.com/city/Nangal/order-online"
    },
    {
    name:"Narnaul",
    link:"https://www.swiggy.com/city/Narnaul/order-online"
    },
    {
    name:"Naraingarh",
    link:"https://www.swiggy.com/city/Naraingarh/order-online"
    },
    {
    name:"Himmatnagar",
    link:"https://www.swiggy.com/city/Himmatnagar/order-online"
    },
    {
    name:"Dausa",
    link:"https://www.swiggy.com/city/Dausa/order-online"
    },
    {
    name:"Jahanabad",
    link:"https://www.swiggy.com/city/Jahanabad/order-online"
    },
    {
    name:"Samastipur",
    link:"https://www.swiggy.com/city/Samastipur/order-online"
    },
    {
    name:"Purnea",
    link:"https://www.swiggy.com/city/Purnea/order-online"
    },
    {
    name:"Malda",
    link:"https://www.swiggy.com/city/Malda/order-online"
    },
    {
    name:"Tuni",
    link:"https://www.swiggy.com/city/Tuni/order-online"
    },
    {
    name:"Puttur",
    link:"https://www.swiggy.com/city/Puttur/order-online"
    },
    {
    name:"Rayachoty",
    link:"https://www.swiggy.com/city/Rayachoty/order-online"
    },
    {
    name:"Medak",
    link:"https://www.swiggy.com/city/Medak/order-online"
    },
    {
    name:"Nirmal",
    link:"https://www.swiggy.com/city/Nirmal/order-online"
    },
    {
    name:"Mirzapur",
    link:"https://www.swiggy.com/city/Mirzapur/order-online"
    },
    {
    name:"Tanuku",
    link:"https://www.swiggy.com/city/Tanuku/order-online"
    },
    {
    name:"Dahod",
    link:"https://www.swiggy.com/city/Dahod/order-online"
    },
    {
    name:"Barmer",
    link:"https://www.swiggy.com/city/Barmer/order-online"
    },
    {
    name:"Gangapur City",
    link:"https://www.swiggy.com/city/Gangapur City/order-online"
    },
    {
    name:"Mandi Gobindgarh",
    link:"https://www.swiggy.com/city/Mandi Gobindgarh/order-online"
    },
    {
    name:"Tarn Taran Sahib",
    link:"https://www.swiggy.com/city/Tarn Taran Sahib/order-online"
    },
    {
    name:"Nakodar",
    link:"https://www.swiggy.com/city/Nakodar/order-online"
    },
    {
    name:"Ankleshwar",
    link:"https://www.swiggy.com/city/sirsa/order-online"
    },
    {
    name:"Vyara",
    link:"https://www.swiggy.com/city/Vyara/order-online"
    },
    {
    name:"Bardoli",
    link:"https://www.swiggy.com/city/Bardoli/order-online"
    },
    {
    name:"Halol",
    link:"https://www.swiggy.com/city/Halol/order-online"
    },
    {
    name:"Bijnor",
    link:"https://www.swiggy.com/city/Bijnor/order-online"
    },
    {
    name:"Sawantwadi",
    link:"https://www.swiggy.com/city/Sawantwadi/order-online"
    },
    {
    name:"Shrirampur",
    link:"https://www.swiggy.com/city/Shrirampur/order-online"
    },
    {
    name:"Sangamner",
    link:"https://www.swiggy.com/city/Sangamner/order-online"
    },
    {
    name:"Baramati",
    link:"https://www.swiggy.com/city/Baramati/order-online"
    },
    {
    name:"Betul",
    link:"https://www.swiggy.com/city/Betul/order-online"
    },
    {
    name:"Chhatarpur",
    link:"https://www.swiggy.com/city/Chhatarpur/order-online"
    },
    {
    name:"Datia",
    link:"https://www.swiggy.com/city/Datia/order-online"
    },
    {
    name:"Balaghat",
    link:"https://www.swiggy.com/city/Balaghat/order-online"
    },
    {
    name:"Sivakasi",
    link:"https://www.swiggy.com/city/Sivakasi/order-online"
    },
    {
    name:"Viluppuram",
    link:"https://www.swiggy.com/city/Viluppuram/order-online"
    },
    {
    name:"Ramanathapuram",
    link:"https://www.swiggy.com/city/Ramanathapuram/order-online"
    },
    {
    name:"Sirsi",
    link:"https://www.swiggy.com/city/Sirsi/order-online"
    },
    {
    name:"Kodaikanal",
    link:"https://www.swiggy.com/city/Kodaikanal/order-online"
    },
    {
    name:"Theni",
    link:"https://www.swiggy.com/city/Theni/order-online"
    },
    {
    name:"Karur",
    link:"https://www.swiggy.com/city/Karur/order-online"
    },
    {
    name:"Karwar",
    link:"https://www.swiggy.com/city/Karwar/order-online"
    },
    {
    name:"Sindhanur",
    link:"https://www.swiggy.com/city/Sindhanur/order-online"
    },
    {
    name:"Kannur",
    link:"https://www.swiggy.com/city/Kannur/order-online"
    },
    {
    name:"Noida 1",
    link:"https://www.swiggy.com/city/Noida 1/order-online"
    },
    {
    name:"Karunagappaly",
    link:"https://www.swiggy.com/city/Karunagappaly/order-online"
    },
    {
    name:"Thiruvalla",
    link:"https://www.swiggy.com/city/Thiruvalla/order-online"
    },
    {
    name:"Thodupuzha",
    link:"https://www.swiggy.com/city/Thodupuzha/order-online"
    },
    {
    name:"Kadiri",
    link:"https://www.swiggy.com/city/Kadiri/order-online"
    },
    {
    name:"Kavali",
    link:"https://www.swiggy.com/city/Kavali/order-online"
    },
    {
    name:"Tezpur",
    link:"https://www.swiggy.com/city/Tezpur/order-online"
    },
    {
    name:"Kayamkulam",
    link:"https://www.swiggy.com/city/Kayamkulam/order-online"
    },
    {
    name:"Kottarakkara",
    link:"https://www.swiggy.com/city/Kottarakkara/order-online"
    },
    {
    name:"Mandi Dabwali",
    link:"https://www.swiggy.com/city/Mandi Dabwali/order-online"
    },
    {
    name:"Fatehabad",
    link:"https://www.swiggy.com/city/Fatehabad/order-online"
    },
    {
    name:"Jagraon",
    link:"https://www.swiggy.com/city/Jagraon/order-online"
    },
    {
    name:"Mansa",
    link:"https://www.swiggy.com/city/Mansa/order-online"
    },
    {
    name:"Pinjore City",
    link:"https://www.swiggy.com/city/Pinjore City/order-online"
    },
    {
    name:"Fazilka",
    link:"https://www.swiggy.com/city/Fazilka/order-online"
    },
    {
    name:"Baddi",
    link:"https://www.swiggy.com/city/Baddi/order-online"
    },
    {
    name:"Solan",
    link:"https://www.swiggy.com/city/Solan/order-online"
    },
    {
    name:"Daltonganj",
    link:"https://www.swiggy.com/city/Daltonganj/order-online"
    },
    {
    name:"Balangir",
    link:"https://www.swiggy.com/city/Balangir/order-online"
    },
    {
    name:"Paonta Sahib",
    link:"https://www.swiggy.com/city/Paonta Sahib/order-online"
    },
    {
    name:"Kothagudem",
    link:"https://www.swiggy.com/city/Kothagudem/order-online"
    },
    {
    name:"Hansi",
    link:"https://www.swiggy.com/city/Hansi/order-online"
    },
    {
    name:"Aurangabad_Bihar",
    link:"https://www.swiggy.com/city/Aurangabad_Bihar/order-online"
    },
    {
    name:"Charkhi Dadri",
    link:"https://www.swiggy.com/city/Charkhi Dadri/order-online"
    },
    {
    name:"Gopalganj",
    link:"https://www.swiggy.com/city/Gopalganj/order-online"
    },
    {
    name:"Jharsuguda",
    link:"https://www.swiggy.com/city/Jharsuguda/order-online"
    },
    {
    name:"Tohana",
    link:"https://www.swiggy.com/city/Tohana/order-online"
    },
    {
    name:"Jhalawar",
    link:"https://www.swiggy.com/city/Jhalawar/order-online"
    },
    {
    name:"Sivasagar",
    link:"https://www.swiggy.com/city/Sivasagar/order-online"
    },
    {
    name:"Bagdogra",
    link:"https://www.swiggy.com/city/Bagdogra/order-online"
    },
    {
    name:"Angul",
    link:"https://www.swiggy.com/city/Angul/order-online"
    },
    {
    name:"Kendrapada",
    link:"https://www.swiggy.com/city/Kendrapada/order-online"
    },
    {
    name:"Mallapuram (Do not Use)",
    link:"https://www.swiggy.com/city/Mallapuram/order-online"
    },
    {
    name:"Veraval",
    link:"https://www.swiggy.com/city/Veraval/order-online"
    },
    {
    name:"Daman",
    link:"https://www.swiggy.com/city/Daman/order-online"
    },
    {
    name:"Chiplun",
    link:"https://www.swiggy.com/city/Chiplun/order-online"
    },
    {
    name:"Silvassa",
    link:"https://www.swiggy.com/city/Silvassa/order-online"
    },
    {
    name:"Bapatla&Chirala",
    link:"https://www.swiggy.com/city/Bapatla&Chirala/order-online"
    },
    {
    name:"Lonavla",
    link:"https://www.swiggy.com/city/Lonavla/order-online"
    },
    {
    name:"Bongaigaon",
    link:"https://www.swiggy.com/city/Bongaigaon/order-online"
    },
    {
    name:"Golaghat",
    link:"https://www.swiggy.com/city/Golaghat/order-online"
    },
    {
    name:"Duliajan",
    link:"https://www.swiggy.com/city/Duliajan/order-online"
    },
    {
    name:"Ramnagar",
    link:"https://www.swiggy.com/city/Ramnagar/order-online"
    },
    {
    name:"Bolpur",
    link:"https://www.swiggy.com/city/Bolpur/order-online"
    },
    {
    name:"Madhubani",
    link:"https://www.swiggy.com/city/Madhubani/order-online"
    },
    {
    name:"Balasore",
    link:"https://www.swiggy.com/city/Balasore/order-online"
    },
    {
    name:"Palampur",
    link:"https://www.swiggy.com/city/Palampur/order-online"
    },
    {
    name:"Kotdwar",
    link:"https://www.swiggy.com/city/Kotdwar/order-online"
    },
    {
    name:"Koppal",
    link:"https://www.swiggy.com/city/Koppal/order-online"
    },
    {
    name:"Chikhli",
    link:"https://www.swiggy.com/city/Chikhli/order-online"
    },
    {
    name:"Dahanu",
    link:"https://www.swiggy.com/city/Dahanu/order-online"
    },
     {
    name:"Itanagar",
    link:"https://www.swiggy.com/city/Itanagar/order-online"
    },
     {
    name:"Rangpo",
    link:"https://www.swiggy.com/city/Rangpo/order-online"
    },
     {
    name:"Aizawl",
    link:"https://www.swiggy.com/city/Aizawl/order-online"
    },
     {
    name:"Gangtok",
    link:"https://www.swiggy.com/city/Gangtok/order-online"
    },
     {
    name:"Mayiladuthurai",
    link:"https://www.swiggy.com/city/Mayiladuthurai/order-online"
    },
     {
    name:"Kannauj",
    link:"https://www.swiggy.com/city/Kannauj/order-online"
    },
    {
    name:"Cooch Behar",
    link:"https://www.swiggy.com/city/Cooch Behar/order-online"
    },
     {
    name:"Jaigaon",
    link:"https://www.swiggy.com/city/Jaigaon/order-online"
    },
     {
    name:"Palani",
    link:"https://www.swiggy.com/city/Palani/order-online"
    },
     {
    name:"Bilimora",
    link:"https://www.swiggy.com/city/Bilimora/order-online"
    },
     {
    name:"Udhampur",
    link:"https://www.swiggy.com/city/Udhampur/order-online"
    },
     {
    name:"Boisar",
    link:"https://www.swiggy.com/city/Boisar/order-online"
    },
     {
    name:"Kohima",
    link:"https://www.swiggy.com/city/Kohima/order-online"
    },
     {
    name:"Naharlagun",
    link:"https://www.swiggy.com/city/Naharlagun/order-online"
    },
     {
    name:"Dumka",
    link:"https://www.swiggy.com/city/Dumka/order-online"
    },
     {
    name:"Rajsamand",
    link:"https://www.swiggy.com/city/Rajsamand/order-online"
    },
     {
    name:"Gauriganj",
    link:"https://www.swiggy.com/city/Gauriganj/order-online"
    },
     {
    name:"Bodinayakanur",
    link:"https://www.swiggy.com/city/Bodinayakanur/order-online"
    },
     {
    name:"Bhawanipatna",
    link:"https://www.swiggy.com/city/Bhawanipatna/order-online"
    },
     {
    name:"Baran",
    link:"https://www.swiggy.com/city/Baran/order-online"
    },
     {
    name:"Narsinghpur",
    link:"https://www.swiggy.com/city/Narsinghpur/order-online"
    },
     {
    name:"Uran Islampur",
    link:"https://www.swiggy.com/city/UranIslampur/order-online"
    },
     {
    name:"Kovilpatti",
    link:"https://www.swiggy.com/city/Kovilpatti/order-online"
    },
     {
    name:"Kasaragod",
    link:"https://www.swiggy.com/city/Kasaragod/order-online"
    },
     {
    name:"Pusad",
    link:"https://www.swiggy.com/city/Pusad/order-online"
    },
     {
    name:"Kendujhar",
    link:"https://www.swiggy.com/city/Kendujhar/order-online"
    },
     {
    name:"Manali",
    link:"https://www.swiggy.com/city/Manali/order-online"
    },
     {
    name:"Diu",
    link:"https://www.swiggy.com/city/Diu/order-online"
    },
     {
    name:"Khamgaon",
    link:"https://www.swiggy.com/city/Khamgaon/order-online"
    },

     {
     name:"Ramanagara",
     link:"https://www.swiggy.com/city/Ramanagara/order-online"
    },
     {
    name:"Alipurduar",
    link:"https://www.swiggy.com/city/Alipurduar/order-online"
    },
     {
    name:"Almora",
    link:"https://www.swiggy.com/city/Almora/order-online"
    },
     {
    name:"Jhargram",
    link:"https://www.swiggy.com/city/Jhargram/order-online"
    },
     {
    name:"Arambagh",
    link:"https://www.swiggy.com/city/Arambagh/order-online"
    },
     {
    name:"Bhadohi",
    link:"https://www.swiggy.com/city/Bhadohi/order-online"
    },
     {
    name:"Tenkasi",
    link:"https://www.swiggy.com/city/Tenkasi/order-online"
    },
     {
    name:"Srivilliputhur",
    link:"https://www.swiggy.com/city/Srivilliputhur/order-online"
    },
     {
    name:"Chidambaram",
    link:"https://www.swiggy.com/city/Chidambaram/order-online"
    },
     {
    name:"Rajgarh",
    link:"https://www.swiggy.com/city/Rajgarh/order-online"
    },
     {
    name:"Pratapgarh",
    link:"https://www.swiggy.com/city/Pratapgarh/order-online"
    },
     {
    name:"Washim",
    link:"https://www.swiggy.com/city/Washim/order-online"
    },
     {
    name:"Mandi HP",
    link:"https://www.swiggy.com/city/Mandi/order-online"
    },

     {
    name:"Ranaghat",
    link:"https://www.swiggy.com/city/Ranaghat/order-online"
    },
     {
    name:"Raghunathpur",
    link:"https://www.swiggy.com/city/Raghunathpur/order-online"
    },

    {
    name:"Suri",
    link:"https://www.swiggy.com/city/Suri/order-online"
    },

    {
    name:"Kadayanallur",
    link:"https://www.swiggy.com/city/Kadayanallur/order-online"
    },

    {
    name:"Thiruvarur",
    link:"https://www.swiggy.com/city/Thiruvarur/order-online"
    },

    {
    name:"Ranaghat-WB",
    link:"https://www.swiggy.com/city/Ranaghat-WB/order-online"
    },

    {
    name:"Idukki",
    link:"https://www.swiggy.com/city/Idukki/order-online"
    },

    {
    name:"Wayanad",
    link:"https://www.swiggy.com/city/Wayanad/order-online"
    },

    {
    name:"Perambalur",
    link:"https://www.swiggy.com/city/Perambalur/order-online"
    },

    {
    name:"Paramakudi",
    link:"https://www.swiggy.com/city/Paramakudi/order-online"
    },


    {
    name:"Khopoli",
    link:"https://www.swiggy.com/city/Khopoli/order-online"
    },

    {
    name:"Bela Pratapgarh",
    link:"https://www.swiggy.com/city/BelaPratapgarh/order-online"
    },

    {
    name:"Mahoba",
    link:"https://www.swiggy.com/city/Mahoba/order-online"
    },

    {
    name:"Sitamarhi",
    link:"https://www.swiggy.com/city/Sitamarhi/order-online"
    },

    {
    name:"Chakdaha",
    link:"https://www.swiggy.com/city/Chakdaha/order-online"
    },

    {
    name:"Khalilabad",
    link:"https://www.swiggy.com/city/Khalilabad/order-online"
    },

    {
    name:"Pattukkottai",
    link:"https://www.swiggy.com/city/Pattukkottai/order-online"
    },

    {
    name:"Tindivanam",
    link:"https://www.swiggy.com/city/Tindivanam/order-online"
    },

    {
    name:"Tiruttani",
    link:"https://www.swiggy.com/city/Tiruttani/order-online"
    },

    {
    name:"Gangarampur",
    link:"https://www.swiggy.com/city/Gangarampur/order-online"
    },

    {
    name:"Dharapuram",
    link:"https://www.swiggy.com/city/Dharapuram/order-online"
    },

    {
    name:"Arakkonam",
    link:"https://www.swiggy.com/city/Arakkonam/order-online"
    },

    {
    name:"Sirkali",
    link:"https://www.swiggy.com/city/Sirkali/order-online"
    },

    {
    name:"Aruppukottai",
    link:"https://www.swiggy.com/city/Aruppukottai/order-online"
    },
    {
    name:"Mettupalayam",
    link:"https://www.swiggy.com/city/Mettupalayam/order-online"
    },
    {
    name:"Digboi",
    link:"https://www.swiggy.com/city/Digboi/order-online"
    },
    {
    name:"Biswanath Chariali",
    link:"https://www.swiggy.com/city/BiswanathChariali/order-online"
    },
    {
    name:"Nalbari",
    link:"https://www.swiggy.com/city/Nalbari/order-online"
    },
    {
    name:"Shirdi city",
    link:"https://www.swiggy.com/city/Shirdi/order-online"
    },
    {
    name:"Mukerian",
    link:"https://www.swiggy.com/city/Mukerian/order-online"
    },
    {
    name:"Hosur",
    link:"https://www.swiggy.com/city/Hosur/order-online"
    },
    {
    name:"Palakollu",
    link:"https://www.swiggy.com/city/Palakollu/order-online"
    },
    {
    name:"Amalapuram",
    link:"https://www.swiggy.com/city/Amalapuram/order-online"
    },
    {
    name:"Ravulapalem",
    link:"https://www.swiggy.com/city/Ravulapalem/order-online"
    },
    {
    name:"Narsipatnam",
    link:"https://www.swiggy.com/city/Narsipatnam/order-online"
    },
    {
    name:"Barh",
    link:"https://www.swiggy.com/city/Barh/order-online"
    },
    {
    name:"Palghar",
    link:"https://www.swiggy.com/city/Palghar/order-online"
    },
    {
    name:"Shahdol",
    link:"https://www.swiggy.com/city/Shahdol/order-online"
    },
    {
    name:"Kushalnagar",
    link:"https://www.swiggy.com/city/Kushalnagar/order-online"
    },
    {
    name:"Dungarpur",
    link:"https://www.swiggy.com/city/Dungarpur/order-online"
    },
    {
    name:"Chaibasa",
    link:"https://www.swiggy.com/city/Chaibasa/order-online"
    },
    {
    name:"Haveri",
    link:"https://www.swiggy.com/city/Haveri/order-online"
    },
    {
    name:"Karaikal",
    link:"https://www.swiggy.com/city/Karaikal/order-online"
    },
    {
    name:"Jjajjar",
    link:"https://www.swiggy.com/city/Jjajjar/order-online"
    },
    {
    name:"Kokrajhar",
    link:"https://www.swiggy.com/city/Kokrajhar/order-online"
    },
    {
    name:"Rangia",
    link:"https://www.swiggy.com/city/Rangia/order-online"
    },
    {
    name:"Hamirpur",
    link:"https://www.swiggy.com/city/Hamirpur/order-online"
    },
    {
    name:"Una",
    link:"https://www.swiggy.com/city/Una/order-online"
    },
    {
    name:"Sulthan Bathery",
    link:"https://www.swiggy.com/city/SulthanBathery/order-online"
    },
    {
    name:"Rayagada",
    link:"https://www.swiggy.com/city/Rayagada/order-online"
    },
    {
    name:"Paradeep",
    link:"https://www.swiggy.com/city/Paradeep/order-online"
    },
    {
    name:"Mandapeta",
    link:"https://www.swiggy.com/city/Mandapeta/order-online"
    },
    {
    name:"Jamui",
    link:"https://www.swiggy.com/city/Jamui/order-online"
    },
    {
    name:"Pilkhuwa",
    link:"https://www.swiggy.com/city/Pilkhuwa/order-online"
    },
    {
    name:"Parvathipuram",
    link:"https://www.swiggy.com/city/Parvathipuram/order-online"
    },
    {
    name:"Ambajogai",
    link:"https://www.swiggy.com/city/Ambajogai/order-online"
    },
    {
    name:"Araria",
    link:"https://www.swiggy.com/city/Araria/order-online"
    },
    {
    name:"North Lakhimpur",
    link:"https://www.swiggy.com/city/NorthLakhimpur/order-online"
    },
    {
    name:"Rajampet",
    link:"https://www.swiggy.com/city/Rajampet/order-online"
    },
    {
    name:"Udumalaipettai",
    link:"https://www.swiggy.com/city/Udumalaipettai/order-online"
    },
    {
    name:"Tirupattur",
    link:"https://www.swiggy.com/city/Tirupattur/order-online"
    },
    {
    name:"Hojai",
    link:"https://www.swiggy.com/city/Hojai/order-online"
    },
    {
    name:"Khagaria",
    link:"https://www.swiggy.com/city/Khagaria/order-online"
    },
    {
    name:"Dasuya",
    link:"https://www.swiggy.com/city/Dasuya/order-online"
    },
    {
    name:"Gudur",
    link:"https://www.swiggy.com/city/Gudur/order-online"
    },
    {
    name:"Sullurpeta",
    link:"https://www.swiggy.com/city/Sullurpeta/order-online"
    },
    {
    name:"Piler",
    link:"https://www.swiggy.com/city/Piler/order-online"
    },
    {
    name:"SankaranKoil",
    link:"https://www.swiggy.com/city/SankaranKoil/order-online"
    },
    {
    name:"Nabha",
    link:"https://www.swiggy.com/city/Nabha/order-online"
    },
    {
    name:"LPU - Phagwara",
    link:"https://www.swiggy.com/city/LPUPhagwara/order-online"
    },
    {
    name:"Jangipur",
    link:"https://www.swiggy.com/city/Jangipur/order-online"
    },
    {
    name:"Roha",
    link:"https://www.swiggy.com/city/Roha/order-online"
    },
    {
    name:"Maharajganj",
    link:"https://www.swiggy.com/city/Maharajganj/order-online"
    },
    {
    name:"Kallakurichi",
    link:"https://www.swiggy.com/city/Kallakurichi/order-online"
    },
    {
    name:"Kalimpong",
    link:"https://www.swiggy.com/city/Kalimpong/order-online"
    },
    {
    name:"Sundernagar",
    link:"https://www.swiggy.com/city/Sundernagar/order-online"
    },
    {
    name:"Nawada",
    link:"https://www.swiggy.com/city/Nawada/order-online"
    },
    {
    name:"Forbesganj",
    link:"https://www.swiggy.com/city/Forbesganj/order-online"
    },
    {
    name:"Mokameh Khas",
    link:"https://www.swiggy.com/city/MokamehKhas/order-online"
    },
    {
    name:"Bazpur",
    link:"https://www.swiggy.com/city/Bazpur/order-online"
    },
    {
    name:"Lakhisarai",
    link:"https://www.swiggy.com/city/Lakhisarai/order-online"
    },
    {
    name:"Rameswaram",
    link:"https://www.swiggy.com/city/Rameswaram/order-online"
    },
    {
    name:"Sahjanwa",
    link:"https://www.swiggy.com/city/Sahjanwa/order-online"
    },
    {
    name:"Siddharthnagar",
    link:"https://www.swiggy.com/city/Siddharthnagar/order-online"
    },
    {
    name:"Nanjangud",
    link:"https://www.swiggy.com/city/Nanjangud/order-online"
    },
    {
    name:"Chamarajanagar",
    link:"https://www.swiggy.com/city/Chamarajanagar/order-online"
    },
    {
    name:"Kurali",
    link:"https://www.swiggy.com/city/Kurali/order-online"
    },
    {
    name:"Sundar Nagar",
    link:"https://www.swiggy.com/city/SundarNagar/order-online"
    },
    {
    name:"Bobbili",
    link:"https://www.swiggy.com/city/Bobbili/order-online"
    },
    {
    name:"Jangaon",
    link:"https://www.swiggy.com/city/Jangaon/order-online"
    },
    {
    name:"Banswara",
    link:"https://www.swiggy.com/city/Banswara/order-online"
    },
    {
    name:"Sundergarh",
    link:"https://www.swiggy.com/city/Sundergarh/order-online"
    },
    {
    name:"Godda",
    link:"https://www.swiggy.com/city/Godda/order-online"
    },
    {
    name:"Madhupur",
    link:"https://www.swiggy.com/city/Madhupur/order-online"
    },
    {
    name:"Katwa",
    link:"https://www.swiggy.com/city/Katwa/order-online"
    },
    {
    name:"Dhupguri",
    link:"https://www.swiggy.com/city/Dhupguri/order-online"
    },
    {
    name:"Contai",
    link:"https://www.swiggy.com/city/sirsa/order-online"
    },
    {
    name:"Baramulla",
    link:"https://www.swiggy.com/city/Baramulla/order-online"
    },
    {
    name:"Kangeyam",
    link:"https://www.swiggy.com/city/Kangeyam/order-online"
    },
    {
    name:"Naugachia",
    link:"https://www.swiggy.com/city/Naugachia/order-online"
    },
    {
    name:"Madhepura",
    link:"https://www.swiggy.com/city/Madhepura/order-online"
    },
    {
    name:"Jamkhambhaliya",
    link:"https://www.swiggy.com/city/Jamkhambhaliya/order-online"
    },
    {
    name:"Mundra",
    link:"https://www.swiggy.com/city/Mundra/order-online"
    },
    {
    name:"Patan",
    link:"https://www.swiggy.com/city/Patan/order-online"
    },
    {
    name:"Mahuva",
    link:"https://www.swiggy.com/city/Mahuva/order-online"
    },
    {
    name:"Attur",
    link:"https://www.swiggy.com/city/Attur/order-online"
    },
    {
    name:"Pen",
    link:"https://www.swiggy.com/city/Pen/order-online"
    },
    {
    name:"Mandla",
    link:"https://www.swiggy.com/city/Mandla/order-online"
    },
    {
    name:"Contai",
    link:"https://www.swiggy.com/city/Contai/order-online"
    },
    {
    name:"Contai",
    link:"https://www.swiggy.com/city/sirsa/order-online"
    },

    {
    name:"Sidhi",
    link:"https://www.swiggy.com/city/Sidhi/order-online"
    },
    {
    name:"Lakshadweep",
    link:"https://www.swiggy.com/city/Lakshadweep/order-online"
    },
    {
    name:"Chitrakoot",
    link:"https://www.swiggy.com/city/Chitrakoot/order-online"
    },
    {
    name:"Rajam",
    link:"https://www.swiggy.com/city/Rajam/order-online"
    },
    {
    name:"Nippani",
    link:"https://www.swiggy.com/city/Nippani/order-online"
    },
    {
    name:"Sankeshwar",
    link:"https://www.swiggy.com/city/Sankeshwar/order-online"
    },
    {
    name:"Chikkodi",
    link:"https://www.swiggy.com/city/Chikkodi/order-online"
    },
    {
    name:"Modasa",
    link:"https://www.swiggy.com/city/Modasa/order-online"
    },
    {
    name:"Bavla",
    link:"https://www.swiggy.com/city/Bavla/order-online"
    },
    {
    name:"Puttur_AP",
    link:"https://www.swiggy.com/city/Puttur_AP/order-online"
    },
    {
    name:"Sinnar",
    link:"https://www.swiggy.com/city/Sinnar/order-online"
    },
    {
    name:"singur",
    link:"https://www.swiggy.com/city/singur/order-online"
    },
    {
    name:"Nelamangala",
    link:"https://www.swiggy.com/city/Nelamangala/order-online"
    },
    {
    name:"Srinagar Uttarakhand",
    link:"https://www.swiggy.com/city/Srinagar Uttarakhand/order-online"
    },
    {
    name:"Dhampur",
    link:"https://www.swiggy.com/city/Dhampur/order-online"
    },
];


const CityList = () => {

  const [showAll, setshowAll] = useState(false);


  const limit = 11

  const visibleCities = showAll ? cities : cities.slice(0, limit);

  return (

   <div style={{padding: "40px 100px", marginLeft:"50px"}}>
   <h2 style={{ fontSize:"28px", fontWeight:"bold"}}>
        Cities with Food Delivery
      </h2>


      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
          gap: "15px",
          maxWidth: "1000px",
          margin: "0 auto",
        }}
      >
      {visibleCities.map((city, index) => (
          <a
            key={index}
            href={city.link}
            target="_blank"
            rel="noopener noreferrer"
            style={{
  
            padding: "15px 18px",
              borderRadius: "12px",
              backgroundColor: "#f5f5f5",
              color: "#535665",
              textDecoration: "none",
              fontSize: "15px",
              fontWeight: "500",
              textAlign: "center",
              transition: "all 0.3s ease",
              border: "1px solid #e2e2e2",
            }}

          >
            Order food online in <br /> {city.name}
          </a>
       ))}
          
    {!showAll && cities.length > limit && (
        
          <button
            onClick={() => setshowAll(true)}
            style={{
              padding: "15px 18px",
              borderRadius: "12px",
              backgroundColor: "#f5f5f5",
              color: "#fc8019",
              fontSize: "15px",
              fontWeight: "600",
              cursor: "pointer",
              border: "1px solid #e2e2e2",
              textAlign: "center",
              transition: "all 0.3s ease",

            }}
          >
            Show More ▼
          </button>
      )}
    </div>
    </div>

  );
};
export default CityList



